### ISSUE TITLE
편지쓰기 페이지 구현

### ISSUE THREAD

**Issue by easyhyun00** [dnd-side-project/dnd-10th-4-frontend#55]
# ✨ Feature

### 편지쓰기 페이지 
- path `/write`
- **편지쓰기 UI 구현** 
  - 폼 내용 다 작성안하고 보내기 눌렀을 때 어떻게 되는지는 아직 모르겠음 
  - 작성하기 버튼 두 개??
  - 백그라운드 아직 모름
- **편지쓰기 form 기능 구현**
  - 폼에 제출해야 되는 내용 
    - 받는 사람 정보
      - 나이(슬라이더)
      - 성별(1개만 선택)
      - 고민(1개만 선택)
    - 편지 내용(300자 이하, 최소 n자 이상 있으면 좋을 듯)
    - 보내는 날짜
    - 사진(+ 이미지 크롭 기능)
    - 사용자 정보(헤더에 Bearer 토큰)
  - React-Hook-Form 과 Zod 사용 
    - FormProvider 사용하여 컴포넌트 간 폼 데이터 공유 
```js
{
    "content": "안녕하세요.",
    "equalGender": true, // 동성 true, 모두에게 false
    "ageRangeStart": 20,
    "ageRangeEnd": 30,
    "worryType": "ETC"
    "image":  e.target.files[0] 내용? // File
}
```
- **편지쓰기 API 요청 구현**
  - Axios, Tanstack Query 
  - `/letter/write`(임시) - POST
- **편지쓰기 msw 모킹 작성**

### TODO

- [x] 편지쓰기 UI 구현
- [x] 편지쓰기 form 기능 구현
- [ ] 편지쓰기 API 요청 구현 & msw 모킹 작성
